import type { Metadata } from "next";
import "./globals.css";
import { Lexend, Limelight } from 'next/font/google';

const limelight = Limelight({
  subsets: ['latin'],
  display: 'swap',
  weight: '400'
});

const lexend = Lexend({
  subsets: ['latin'],
  display: 'swap',
  weight: '400'
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
